### PR TITLE
Create aws.yml

### PR DESCRIPTION
**Pull request by qchio**
name: ENS Build and Test

on:
  push:
    branches:
      - main pull_request: branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code uses: actions/checkout@v2

      # Add steps to build and test your ENS project here
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

### CODE REVIEW

**Comment by qchio** [comment]
name: ENS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and test your ENS project here
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

**Review by qchio — COMMENTED** [review]
name: ENS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and test your ENS project here
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

**Review by eianenee — COMMENTED** [review]
name: Build and Test ENS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

**Review by eianenee — COMMENTED** [review]
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Install dependencies
    run: npm install

  - name: Build project
    run: npm run build

  - name: Run tests
    run: npm test

**Pull request merged**
